### ISSUE TITLE
new flashbots_getWork rpc for reporting job profitability

### ISSUE THREAD

**Issue by thegostep** [flashbots/mev-geth#103]
# Rationale

Many miners are currently using default node configuration to create blocks. This means they use a 3 second recommit interval and are attempting to merge at most 3 bundles.

The goal of MEV-Geth should be to use all available resources to find and output more valuable blocks as quickly as possible which allows a process running on a separate machine to profit switch and update tasks if the new job is more valuable.

# Implementation

Add new RPC method `flashbots_getWork` to MEV-Geth which adds a new block reward including MEV to `eth_getWork` RPC result.

The block reward should match the profit number used in the mining worker: https://github.com/flashbots/mev-geth/blob/516e2c3982109dd4176f3eae71015dd385f65ea2/miner/worker.go#L105

```
flashbots_getWork

Returns the hash of the current block, the seedHash, the boundary condition to be met ("target"), and the profit from mining this block.

Parameters

none

Returns

Array - Array with the following properties:
- DATA, 32 Bytes - current block header pow-hash.
- DATA, 32 Bytes - the seed hash used for the DAG.
- DATA, 32 Bytes - the boundary condition ("target"), 2^256 / difficulty.
- STRING - hex encoded block number.
- QUANTITY, 256 Bits - the profit generated from this block.
```

**Comment by jparyani** [comment]
Done in #106
