### ISSUE TITLE
value returned by eth_callBundle is always 32-bytes

### ISSUE THREAD

**Issue by epheph** [flashbots/mev-geth#19]
eth_callBundle returns "value" as part of its array. that value is 32-bytes of 0's when the return is empty and the first 32-bytes of value when the value is longer than 32-bytes.

**Comment by jparyani** [comment]
Fixed in a9ba2734fc56399ebac1dfd456cb4232443dbc21. I added support for `revert` messages as well, but sadly the evm function we're using to simulate doesn't seem to return them properly.
