### ISSUE TITLE
move optional features to feature branches

### ISSUE THREAD

**Issue by thegostep** [flashbots/mev-geth#20]
Since mining pool infrastructure is highly customized, mev-geth would benefit from modularizing the feature set into atomic components. Lets move each of these features in their own branch.

1. (base) bundle worker with `eth_sendBundle` RPC
2. (feature) profit switcher
3. (feature) `eth_callBundle` RPC

**Comment by fiiiu** [comment]
After discussion with @jparyani we settled on:

1. `master` branch: our recommended way of running mev-geth for miners, including bundle processing and the profit switching logic.
2. `master-barebones` branch: minimal bundle processing functionality _without_ profit switching.

We will also keep two internal branches for development:

3. `aws-goerli` branch: includes bundle processing, profit switching, and bundle simulation, and is the release branch used for testing.
4. `aws-mainnet` branch: internal branch mimicking `aws-goerli`, where changes are pushed once testing in Görli is complete.

Note also that _all_ branches also contain  documentation (`README.md` and CI config files).
