### ISSUE TITLE
add `eth_sendMegabundle` RPC

### ISSUE THREAD

**Issue by thegostep** [flashbots/mev-geth#52]
## Description
eth_sendMegaBundle would allow for sending bundles which bypass the bundle scoring auction and instead are directly inserted in a block in the multi-worker

the mev-geth node is reponsible for filling the remaining space in the block with transactions from the mempool

the rpc parameters would be:
```json
{
    "transaction_list": [],
    "timestamp": "",
    "coinbase_diff": "",
    "coinbase": "0x",
    "parent_hash": "",
}
```

## Specification
https://docs.flashbots.net/flashbots-auction/miners/mev-geth-spec/v04

**Comment by bogatyy** [comment]
Met with @tkstanczak @jparyani @pgebheim , decided the following:
1) RLP is decidedly better than JSON (which was only used on Flashbots relay outside Geth), so definitely serializing via RLP
2) `blockNumber` is going to be a `uint`. Jason thinks it's cleaner and hex block numbers were a mistake to begin with. Ivan had a slight preference for keeping compatibility with the standard block number format (hex), but ok with uint too.
3) For RLP serialization, we will have a separate data structure. It will not have a `relaySignature` field, and all the fields will be mandatory (e.g. mandatory zeros for minTimestamp, maxTimestamp). Goal is to make it 100% obvious that serializations are deterministic, and not worry about `nil`s vs zeros.

**Comment by bogatyy** [comment]
Pushed out a fix to conform to the meeting decisions above, in the PR https://github.com/flashbots/mev-geth/pull/86

Also, as FYI, here is an example of a megabundle builder in Python https://github.com/Mining-DAO/examples/blob/main/megabundle_sender.py
