### ISSUE TITLE
A couple searcher suggestions for the new v0.2 code

### ISSUE THREAD

**Issue by riposteX** [flashbots/mev-geth#66]
In computeBundleGas, if a transaction with the same nonce exists in the mempool, it's completely ignored for the purposes of calculating the miner bribe/reward.

This is not ideal for me as I plan to submit same-nonce transactions to both FB and the mempool to maximize my chances of winning.

A better approach would be to ignore the gas fees if a same nonce transaction exists, but include any direct coinbase transfers.

It's not clear to me why you're complicating things with gas fees at all, though. Seems like it would be much cleaner to only consider direct coinbase transfers for all transactions.

Second, when merging bundles, you're currently accepting bundles as long as they don't error and totalEth >= 0. Don't think this second condition can be violated, makes more sense to set as totalEth > 0 so that miners don't waste gas on valueless bundles.

**Comment by jparyani** [comment]
> A better approach would be to ignore the gas fees if a same nonce transaction exists, but include any direct coinbase transfers.

Unfortunately, the current behavior is much safer, since it protects against odd things like people paying directly to miners for other reasons or reorgs. I recommend that you rewrite your bots such that you can use different EOAs for flashbots/non-flashbots.

> Second, when merging bundles, you're currently accepting bundles as long as they don't error and totalEth >= 0. Don't think this second condition can be violated, makes more sense to set as totalEth > 0 so that miners don't waste gas on valueless bundles.

Thanks! Fixed in https://github.com/flashbots/mev-geth/commit/b36e0f0d58ee5222244450ab50345c91194fc065#diff-689874b30f6f905ce6c47cdefeddcf052b467a7936a981f4b6cf38939e10d924R1252

**Comment by riposteX** [comment]
> I recommend that you rewrite your bots such that you can use different EOAs for flashbots/non-flashbots.

Would prefer if the flashbot tx invalidated the mempool tx so I don't have to pay gas fees, but I guess I can always include an extra tx in the bundle to bump the mempool EOA nonce at the cost of a slightly less competitive bid ...
