### ISSUE TITLE
the method `eth_callBundle` does not exist/is not available

### ISSUE THREAD

**Issue by lmittmann** [flashbots/mev-geth#79]
#### System information

Geth version: `geth version`
**MEV Geth Version**: `v1.10.3-mev0.2.3`
```
Geth
Version: 1.10.3-stable
Git Commit: 8e802f88d3294e761162c7aa0400f92ae9df6ccc
Git Commit Date: 20210622
Architecture: amd64
Go Version: go1.16.5
Operating System: linux
GOPATH=
GOROOT=go
```
OS & Version: Windows/Linux/OSX
Ubuntu 20.04
Commit hash : (if `develop`)

#### Expected behaviour

Being able to call `eth_callBundle`.

#### Actual behaviour

Calling `eth_callBundle` returns `bundle execution failed: the method eth_callBundle does not exist/is not available`.

MEV Geth Logs:
```
INFO  Flashbots bundle                         ethToCoinbase=0 gasUsed=0 bundleScore=<nil> bundleLength=0 numBundles=0 worker=1
INFO  Flashbots bundle                         ethToCoinbase=0 gasUsed=0 bundleScore=<nil> bundleLength=0 numBundles=0 worker=3
INFO  Flashbots bundle                         ethToCoinbase=0 gasUsed=0 bundleScore=<nil> bundleLength=0 numBundles=0 worker=2
WARN  Served eth_callBundle                    conn=127.0.0.1:50260 reqid=0                         t="9.2µs"     err="the method eth_callBundle does not exist/is not available"
WARN  Served eth_callBundle                    conn=127.0.0.1:50260 reqid=1                         t="15.222µs"  err="the method eth_callBundle does not exist/is not available"
```

#### Steps to reproduce the behaviour

1. Run MEV Geth `v1.10.3-mev0.2.3`.
2. Call `eth_callBundle`

**Comment by lmittmann** [comment]
The simple reason for not being able to call `eth_callBundle` is that the `CallBundle` func is missing from `internal/ethapi/api.go` on `master`.

I worked around this issue by building from `mev-callbundle@2cc5ee9` instead of `master@v1.10.3-mev0.2.3`. It seems a little counter intuitive that the `eth_callBundle` method is missing from all recent releases. Is there any reason for excluding this method from releases?

**Comment by lmittmann** [comment]
Hi, can the `eth_callBundle` function be included in the `master` branch? The `mev-callbundle` branch is outdated.

**Comment by sambacha** [comment]
> Hi, can the `eth_callBundle` function be included in the `master` branch? The `mev-callbundle` branch is outdated.

https://github.com/openmev/go-ethereum/releases/tag/v1.10.9-mev0.4.0

**Comment by jparyani** [comment]
mev-callbundle has now been merged into the master branch, and the old mev-callbundle is deprecated
