### ISSUE TITLE
Testing Plan for eth_sendMegabundle

### ISSUE THREAD

**Issue by pgebheim** [flashbots/mev-geth#87]
re: https://github.com/flashbots/mev-geth/issues/52

- [x] Negative: Doesn't process bundles from untrusted relays
- [x] Negative: Payment conditional on block coinbase fails when expected
- [x] Negative: Bundle that reverts is ignored
- [x] Negative: Errors if signature error from trusted relay
- [x] Negative: Doesn't process bundles with revert txs
- [x] Negative: Doesn't process bundles with txs that use insufficient gas

------
- [x] Positive: Megabundle of various sizes, verify that they get mined and show up in top of bundle
- [x] Positive: TX fee payments (total profit computed correctly)
- [x] Positive: coinbase transfer fee payments (total profit computed correctly)
- [x] Positive: TX fee & coinbase transfer fee payments (total profit computed correctly)
- [x] Positive: Payment conditional on block coinbase succeeds when expected
- [x] Positive: Bundle with specified reverting txn is successfully mined
- [x] Positive: Miner selects the most profitable of N bundles or 1 megabundle, testing post sides.
- [x] Positive: Submit multiple megabundles from different relayers, verify most profitable one wins
- [x] Positive: Submit multiple bundles and megabundle from different relayers, verify final ordering

**Comment by bogatyy** [comment]
Test cases look great! Tried to think what else is worth testing for correctness, can't think of anything else, we're covered.

If we want to get super fancy, we can also do performance and anti-DDoS testing. Specifically, flood the mev-geth instance with regular bundles, and double-check that megabundles are still processed correctly in a separate worker.
And vice versa, flood one megabundle worker with megabundles and see that the rest of the system does its own processing correctly (in a separate thread, likely on a different CPU core).

**Comment by pgebheim** [comment]
Agreed @bogatyy -- multi-core performance tests would be nice. It seems more like a one-off style test for a start unless there's already a good way to measure that throughput from the integration tests.

@taarushv would love your feedback here too.

**Comment by taarushv** [comment]
Update on this, Was able to reuse [this](https://github.com/taarushv/mev_geth_tests) repo (previously setup for 1559 tests) to run the tests with a docker miner container + relay script over the weekend. Was able to set it up to test the negatives and positives (sans the last 3), will clean up the repo and push the changes on the new main branch first thing in the morning!

**Comment by thegostep** [comment]
feature was completed and released
